name         'stdmod-grafana'
version '0.0.2'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-grafana'
summary      'Puppet module for grafana'
description  'This module installs and manages grafana. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
